# Generated by Django 4.2 on 2024-12-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код верификации'),
        ),
    ]
