# Generated by Django 5.1.2 on 2024-11-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('avatar', models.ImageField(upload_to='products', verbose_name='Изображение')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('price_for_one', models.IntegerField(max_length=100, verbose_name='Цена за штуку')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('last_change_date', models.DateField(verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
