# Generated by Django 5.1.2 on 2024-12-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('product',), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
