# Generated by Django 4.2 on 2024-12-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0014_version_user_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='user_creator',
        ),
        migrations.AddField(
            model_name='product',
            name='user_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
