# Generated by Django 4.2 on 2024-12-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_version_user_creator_product_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_creator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Создатель'),
        ),
    ]
